# Generated by Django 5.0.1 on 2024-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('specialite', models.CharField(max_length=50)),
                ('numero_telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
    ]
