# Generated by Django 5.0.1 on 2024-01-25 16:57

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_medicament_operation_patient_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_rendez_vous',
            field=models.CharField(default=management.models.Consultation, max_length=50),
        ),
    ]
