# Generated by Django 5.0.1 on 2024-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rendezvous_type_rendez_vous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='type_rendez_vous',
            field=models.CharField(max_length=50),
        ),
    ]
